name: Python Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if Python is installed and list available versions
      run: |
        echo "Checking Python version..."
        python3 --version || echo "Python3 is not installed"
        ls /usr/bin/python* || echo "No Python binaries found"

    - name: Install dependencies globally
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz
        tar -xzf allure-2.30.0.tgz -C ~/
        ln -s ~/allure-2.30.0/bin/allure /usr/local/bin/allure
        allure --version

    - name: Run tests and generate Allure results
      run: |
        pytest --alluredir=./allure-results

    - name: Generate single-file Allure report
      run: |
        allure generate --single-file ./allure-results -o ./allure-report


    - name: Upload Allure Report as an artifact 
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: ./allure-report/index.html

