name: Python Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3 -m venv test-env
        source test-env/bin/activate
        pip install --upgrade pip
        pip install pytest requests allure-pytest

    - name: Run tests and generate Allure results
      run: |
        source test-env/bin/activate
        pytest --alluredir=./allure-results

    - name: Generate single-file Allure report
      run: |
        allure generate --single-file ./allure-results -o ./allure-report

    - name: Upload Allure Report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: ./allure-report/index.html

    - name: Save Allure report as a GitHub Pages artifact
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        publish_dir: ./allure-report
